#debug模式，这将会将一些随机事件改为必定发生，这样做是为了方便开发者能固定刷出自己写的内容以检查bug，因此，请永远不要在云端开启此项
Debug_Mode: false
#默认法术可以在这里设为false使其不能使用,ALL是全局禁用，为true时，使用后续设置
MagicALL: true
Magic:
  FIRE_BALL: true
  FLAME_ARROW: true
  THUNDER_WAVE: true
  SHATTER: true
  MAGIC_MISSILE: true
  FROST_ARMOR: true
  THUNDER_CALLING: true
  HOLD_MONSTER: true
  TELEPORT: true
#这是默认的玩家手册数据，如果你需要更改它，你可以直接通过setphb指令来做，或者，你非要在这里改，那就祝你好运。
phbdata:
  ==: org.bukkit.inventory.ItemStack
  v: 2586
  type: WRITTEN_BOOK
  meta:
    ==: ItemMeta
    meta-type: BOOK_SIGNED
    title: 本插件的简单介绍
    author: 旅行者navy_master
    pages:
      - '{"extra":[{"underlined":true,"color":"blue","clickEvent":{"action":"change_page","value":"2"},"text":"MAGIC_MISSILE\n"},{"underlined":true,"color":"blue","clickEvent":{"action":"change_page","value":"3"},"text":"FIRE_BALL\n"},{"underlined":true,"color":"blue","clickEvent":{"action":"change_page","value":"4"},"text":"THUNDER_WAVE\n"},{"underlined":true,"color":"blue","clickEvent":{"action":"change_page","value":"5"},"text":"SHATTER\n"},{"underlined":true,"color":"blue","clickEvent":{"action":"change_page","value":"6"},"text":"FLAME_ARROW\n"},{"underlined":true,"color":"blue","clickEvent":{"action":"change_page","value":"7"},"text":"FROST_ARMOR\n"},{"underlined":true,"color":"blue","clickEvent":{"action":"change_page","value":"8"},"text":"THUNDER_CALLING\n"},{"underlined":true,"color":"blue","clickEvent":{"action":"change_page","value":"9"},"text":"HOLD_MONSTER\n"},{"underlined":true,"color":"blue","clickEvent":{"action":"change_page","value":"10"},"text":"TELEPORT\n"}],"text":"附魔时，有10%概率获得一项主动技能\n拿起物品，右键即可释放，以下为主动技能词条：\n"}'
      - '{"text":"MAGIC_MISSILE\n魔法飞弹\n瞄准目标头部（或者高一点）即可发射三枚跟踪飞弹,冷却3s"}'
      - '{"text":"FIRE_BALL\n火球术\n召唤恶魂火球,冷却1s"}'
      - '{"text":"THUNDER_WAVE\n雷鸣波\n对周围所有其他生物造成伤害，冷却3s"}'
      - '{"text":"SHATTER\n粉碎音波\n对你看向的位置周围所有生物造成伤害,冷却5s"}'
      - '{"text":"FLAME_ARROW\n火焰箭\n对你看向的方向乱箭，无冷却"}'
      - '{"text":"FROST_ARMOR\n凝霜之铠\n获取临时生命，在临时生命消耗完之前，被攻击造成反甲，冷却一分钟"}'
      - '{"text":"THUNDER_CALLING\n召雷术\n对你看向的位置召唤闪电,冷却5s"}'
      - '{"text":"HOLD_MONSTER\n怪物定身术\n定住你看向的非玩家生物3s，需要瞄准目标头部（或者高一点）,冷却6s"}'
      - '{"text":"TELEPORT\n传送术\n传送至目标生物的位置"}'
    resolved: true
#玩家名单，对于首次进入游戏的玩家，向其发送使用/phb的提示,手动添加请写
#- 玩家名
PlayerList: